CREATE TABLE [WFDB].[users](
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Username NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL, 
	Password NVARCHAR(100) NOT NULL,
    Role INT DEFAULT 2 NULL,
	Created_At DATETIME DEFAULT CURRENT_TIMESTAMP NULL, 
);